ticket-server: allow multiple email domains from different google accounts to be validated as ticket-server users
Summary:
Allow the ticket-server to support multiple google domains when performing user verification and blessing.
Allow the ticket-server to support multiple google domains when performing google group lookups
Correct incorrect regex that did not escape special characters `.\([`.

FIXES T37864

Test Plan:
Run local ticket-server
Perform several calls to create a user, and use tickets

```
GB-C02YR4M9LVCG:sandbox.grail aeiser$ grail-access -blesser-google=/@6@wsh@:9002@@35741be6d925abac81c7878ff24e7dfa@s@v23.grail.com@@/blesser/google
I0618 22:23:21.863538   40060 google.go:67] listening: 127.0.0.1:53322
Opening "https://accounts.google.com/o/oauth2/v2/auth?access_type=online&client_id=27162366543-edih9cqc3t8p5hn9ord1k1n7h4oajfhm.apps.googleusercontent.com&redirect_uri=http%3A%2F%2Flocalhost%3A53322&response_type=code&scope=https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fuserinfo.email&state=3f9d3f4f2bec9c70f6c7bd371593e0b1"...
Successfully applied new blessing:
Public key: cc:e5:97:7d:a8:f9:19:b1:fe:60:7d:5d:b3:98:29:26
​---------------- BlessingStore ----------------
Default Blessings                v23.grail.com:google:aeiser@contractors.grail.com
Peer pattern                     Blessings
...                              v23.grail.com:google:aeiser@contractors.grail.com
​---------------- BlessingRoots ----------------
Public key                                        Pattern
98:61:28:77:eb:5f:97:7f:2c:ef:4d:1b:f1:4d:fd:c0   [v23.grail.com]
Expires on 2020-06-25 22:24:42.691220945 -0700 PDT (in 167h59m59.981234945s)
```

```
GB-C02YR4M9LVCG:sandbox.grail aeiser$ grail-access -blesser-google=/@6@wsh@:9002@@35741be6d925abac81c7878ff24e7dfa@s@v23.grail.com@@/blesser/google
I0618 22:24:50.558327   40198 google.go:67] listening: 127.0.0.1:53714
Opening "https://accounts.google.com/o/oauth2/v2/auth?access_type=online&client_id=27162366543-edih9cqc3t8p5hn9ord1k1n7h4oajfhm.apps.googleusercontent.com&redirect_uri=http%3A%2F%2Flocalhost%3A53714&response_type=code&scope=https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fuserinfo.email&state=c09ce502d5980d70a84d227579c9b209"...
ERROR: failed to fetch blessings: grail-access:<rpc.Client>"/@6@wsh@:9002@@35741be6d925abac81c7878ff24e7dfa@s@v23.grail.com@@/blesser/google".BlessGoogle: Error: ID token has a wrong hosted domain: got "sandbox.grail.com", want "grailbio.com,contractors.grail.com"
```

```
GB-C02YR4M9LVCG:sandbox.grail aeiser$ grail-access -blesser-google=/@6@wsh@:9002@@35741be6d925abac81c7878ff24e7dfa@s@v23.grail.com@@/blesser/google
I0618 22:24:58.766576   40203 google.go:67] listening: 127.0.0.1:53723
Opening "https://accounts.google.com/o/oauth2/v2/auth?access_type=online&client_id=27162366543-edih9cqc3t8p5hn9ord1k1n7h4oajfhm.apps.googleusercontent.com&redirect_uri=http%3A%2F%2Flocalhost%3A53723&response_type=code&scope=https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fuserinfo.email&state=a34a4e69355f5f0a77e20c5d2df46722"...
Successfully applied new blessing:
Public key: cc:e5:97:7d:a8:f9:19:b1:fe:60:7d:5d:b3:98:29:26
​---------------- BlessingStore ----------------
Default Blessings                v23.grail.com:google:aeiser@grailbio.com
Peer pattern                     Blessings
...                              v23.grail.com:google:aeiser@grailbio.com
​---------------- BlessingRoots ----------------
Public key                                        Pattern
98:61:28:77:eb:5f:97:7f:2c:ef:4d:1b:f1:4d:fd:c0   [v23.grail.com]
Expires on 2020-06-25 22:25:02.026613997 -0700 PDT (in 167h59m59.992090997s)
```

Before aeiser@contractors.grail.com added to eng/dev
```
GB-C02YR4M9LVCG:sandbox.grail aeiser$ grail-access -blesser-google=/@6@wsh@:9002@@f085cdc756039daeccdb46a54cb2ac2a@s@v23.grail.com@@/blesser/google
Successfully applied new blessing:
Public key: cc:e5:97:7d:a8:f9:19:b1:fe:60:7d:5d:b3:98:29:26
​---------------- BlessingStore ----------------
Default Blessings                v23.grail.com:google:aeiser@contractors.grail.com
Peer pattern                     Blessings
...                              v23.grail.com:google:aeiser@contractors.grail.com
​---------------- BlessingRoots ----------------
Public key                                        Pattern
98:61:28:77:eb:5f:97:7f:2c:ef:4d:1b:f1:4d:fd:c0   [v23.grail.com]
Expires on 2020-06-25 22:41:20.033580147 -0700 PDT (in 167h59m59.993922147s)

GB-C02YR4M9LVCG:sandbox.grail aeiser$ grail-aws //@6@wsh@:9002@@f085cdc756039daeccdb46a54cb2ac2a@s@v23.grail.com@@/eng/dev/admin
no subcommand specified, inferring 'credentials' based on other args
E0618 22:41:33.777187   40932 conncache.go:319] Failed to resolve (wsh, :9002): lookup : no such host
ticket-server:"eng/dev/admin".Get: Access denied: ticket-server:"eng/dev/admin".Get: not authorized to call eng/dev/admin.Get: ticket-server:"eng/dev/admin".Get: [v23.grail.com:google:aeiser@contractors.grail.com] does not have Read access (rejected blessings: [])
```

After adding to eng/dev
```
GB-C02YR4M9LVCG:sandbox.grail aeiser$ grail-aws  /@6@wsh@:9002@@e10baa5fa1ae90e431e077e2ab7531af@s@v23.grail.com@@/eng/dev/admin
no subcommand specified, inferring 'credentials' based on other args
E0618 22:34:08.812232   40729 conncache.go:319] Failed to resolve (wsh, :9002): lookup : no such host
export AWS_ACCESS_KEY_ID=ASIAZAUXVPWNLVEPKWOU
export AWS_SECRET_ACCESS_KEY=XXXX
export AWS_SESSION_TOKEN=YYYY
```

Reviewers: #shared_infrastructure, btoledo

Reviewed By: #shared_infrastructure, btoledo

Subscribers: joshnewman, contractor-aeiser, btoledo, smahadevan

Maniphest Tasks: T37864

Differential Revision: https://phabricator.grailbio.com/D46325

fbshipit-source-id: c6a773e