fsnodefuse: use own cache for READDIRPLUS caching for LOOKUP
Summary:
Use own cache for READDIRPLUS caching for LOOKUP, which makes `TestReaddirplusConcurrent` pass again.

The test currently fails; see output below.

When we traverse directory streams, we add an inode to the directory inode in the Next function so that it may be used by the LOOKUP operation that is interleaved with the traversal when servicing READDIRPLUS operations. We first check if there is an existing child inode, however the test and set is not atomic. This means that two concurrent traversals may each create an inode. This screws up the reference counting used to decide whether a node can be reused by the LOOKUP, as we may orphan one of the inodes, as NewInode does not necessarily return an existing inode if it exists.

The scenario:
# There are two concurrent `dirStream` traversals of directory inode `d`, `dsA` and `dsB`.
# `dsA.Next` and `dsB.Next` are called concurrently while traversing the same child node named `foo`. Both use `GetChild` to check for an existing inode. Both see that there is none.
# `dsA.Next` uses `NewInode` to construct `inodeA` and adds a child, calling `AddChild("foo", inodeA)`. `dsB.Next` uses `NewInode` to construct `inodeB` and adds a child, calling `AddChild("foo", inodeB)`. `inodeB` is different from `inodeA` and replaces `inodeA` as the child named "foo". `inodeA` and `inodeB` each have a reference count of 1.
# The LOOKUP for the `dsB` traversal is called, and the cached `inodeB` is properly used.
# `dsB.Next` is called to continue the traversal. The reference count of `inodeB` is decremented, now 0, so it can no longer be used to service LOOKUP.
# The LOOKUP for the `dsA` traversal is called. `inodeB` is discovered, but with a reference count of 0, we wrongly make the call to `(fsnode.Parent).Child`.

This seems to have started with the move to Ubuntu 20.04.  I do not know why.

Use our own cache for the LOOKUP, for which we eliminate the race condition.  It also eliminates the unusual prior behavior of adding a child on directory traversal.

[BXDS-1666]

Output:
```
❯ bazel test //go/src/github.com/grailbio/base/file/fsnodefuse:go_default_test --test_filter="^TestReaddirplusConcurrent$"
...
==================== Test output for //go/src/github.com/grailbio/base/file/fsnodefuse:go_default_test:
​--- FAIL: TestReaddirplusConcurrent (1.26s)
    --- FAIL: TestReaddirplusConcurrent/iter01 (0.10s)
        readdirplus_test.go:57: numChildren=419 concurrentReaddirs=90
        readdirplus_test.go:70:
                Error Trace:    readdirplus_test.go:70
                                                        readdirplus_test.go:105
                                                        readdirplus_test.go:62
                Error:          Not equal:
                                expected: 0
                                actual  : 3
                Test:           TestReaddirplusConcurrent/iter01
    --- FAIL: TestReaddirplusConcurrent/iter02 (0.04s)
        readdirplus_test.go:57: numChildren=693 concurrentReaddirs=24
        readdirplus_test.go:70:
                Error Trace:    readdirplus_test.go:70
                                                        readdirplus_test.go:105
                                                        readdirplus_test.go:62
                Error:          Not equal:
                                expected: 0
                                actual  : 1
                Test:           TestReaddirplusConcurrent/iter02
    --- FAIL: TestReaddirplusConcurrent/iter05 (0.06s)
        readdirplus_test.go:57: numChildren=322 concurrentReaddirs=85
        readdirplus_test.go:70:
                Error Trace:    readdirplus_test.go:70
                                                        readdirplus_test.go:105
                                                        readdirplus_test.go:62
                Error:          Not equal:
                                expected: 0
                                actual  : 1
                Test:           TestReaddirplusConcurrent/iter05
    --- FAIL: TestReaddirplusConcurrent/iter06 (0.10s)
        readdirplus_test.go:57: numChildren=975 concurrentReaddirs=52
        readdirplus_test.go:70:
                Error Trace:    readdirplus_test.go:70
                                                        readdirplus_test.go:105
                                                        readdirplus_test.go:62
                Error:          Not equal:
                                expected: 0
                                actual  : 1
                Test:           TestReaddirplusConcurrent/iter06
    --- FAIL: TestReaddirplusConcurrent/iter18 (0.02s)
        readdirplus_test.go:57: numChildren=597 concurrentReaddirs=10
        readdirplus_test.go:70:
                Error Trace:    readdirplus_test.go:70
                                                        readdirplus_test.go:105
                                                        readdirplus_test.go:62
                Error:          Not equal:
                                expected: 0
                                actual  : 1
                Test:           TestReaddirplusConcurrent/iter18
FAIL
================================================================================
Target //go/src/github.com/grailbio/base/file/fsnodefuse:go_default_test up-to-date:
  bazel-bin/go/src/github.com/grailbio/base/file/fsnodefuse/go_default_test_/go_default_test
INFO: Elapsed time: 1.469s, Critical Path: 1.28s
INFO: 2 processes: 1 internal, 1 local.
INFO: Build completed, 1 test FAILED, 2 total actions
//go/src/github.com/grailbio/base/file/fsnodefuse:go_default_test        FAILED in 1.3s
  /mnt/bazel/output-root/jjc/a3e42a5764f3aaeb31dd53943e9d787f/execroot/grail/bazel-out/k8-opt/testlogs/go/src/github.com/grailbio/base/file/fsnodefuse/go_default_test/test.log

INFO: Build completed, 1 test FAILED, 2 total actions
```

Test Plan:
Verify that the `fsnodefuse` package tests succeed.
```
bazel test //go/src/github.com/grailbio/base/file/fsnodefuse:go_default_test
```

Manually list multiple directories (with `ls`) in `biofs`, e.g. `ls /mnt/biofs/s3/grail-bigslice/athena-query-result`, and verify that it is not egregiously slow, i.e. a few seconds not many 10s of seconds.

Reviewers: joshnewman

Reviewed By: joshnewman

Subscribers: smahadevan

Differential Revision: https://phabricator.grailbio.com/D71922

fbshipit-source-id: 3330f1b